import type { Product } from "@/app/types/product"

export const products: Product[] = [
  /* ===================== WHEY PROTEIN ===================== */

  {
    id: "on-whey",
    name: "Gold Standard 100% Whey",
    brand: "Optimum Nutrition",
    category: "Whey Protein",
    price: 2499,
    originalPrice: 2874,
    discount: 15,
    rating: 4.5,
    reviews: 12800,
    image: "/image/Whey_protien/Optimum/double_rich_5lb.webp",
    images: [
      "/image/Whey_protien/Optimum/double_rich_5lb.webp",
      "/image/Whey_protien/Optimum/Optimum_Double_Rich_2lb.webp"
    ],
    flavors: [
      { name: "Double Rich Chocolate", price: 2499 },
      { name: "Vanilla Ice Cream", price: 2499 },
    ],
    weight: "2LB / 907GM",
    weights: ["2LB / 907GM", "5LB / 2.27KG"],
    description: "Premium whey protein for muscle growth.",
    keyBenefits: ["24g Protein", "Fast absorption"],
    nutritionalInfo: "24g protein per serving",
    inStock: true,
  },

  {
    id: "dymatize-elite",
    name: "Elite Whey",
    brand: "Dymatize",
    category: "Whey Protein",
    price: 5299,
    originalPrice: 5899,
    discount: 10,
    rating: 4.4,
    reviews: 6200,
    image: "/dymatize.jpg",
    images: ["/dymatize.jpg"],
    flavors: [{ name: "Rich Chocolate", price: 5299 }],
    weight: "5LB / 2.27KG",
    weights: ["5LB / 2.27KG"],
    description: "High quality whey protein.",
    keyBenefits: ["Lean muscle", "Low sugar"],
    nutritionalInfo: "25g protein",
    inStock: true,
  },

  {
    id: "labrada-whey",
    name: "Labrada Whey",
    brand: "Labrada",
    category: "Whey Protein",
    price: 1899,
    originalPrice: 2199,
    discount: 14,
    rating: 4.3,
    reviews: 4100,
    image: "/labrada.jpg",
    images: ["/labrada.jpg"],
    flavors: [
      { name: "Chocolate", price: 1899 },
      { name: "Vanilla", price: 1899 },
      { name: "Mocha", price: 1999 },
    ],
    weight: "1KG",
    weights: ["500G", "1KG", "1.8KG"],
    description: "Clean protein formula.",
    keyBenefits: ["Muscle recovery"],
    nutritionalInfo: "24g protein",
    inStock: true,
  },

  {
    id: "nitrotech",
    name: "Nitro Tech Whey",
    brand: "MuscleTech",
    category: "Whey Protein",
    price: 3099,
    originalPrice: 3599,
    discount: 14,
    rating: 4.6,
    reviews: 9000,
    image: "/nitrotech.jpg",
    images: ["/nitrotech.jpg"],
    flavors: [
      { name: "Double Rich Chocolate", price: 3099 },
      { name: "Cookies & Cream", price: 3199 },
    ],
    weight: "907GM",
    weights: ["450GM", "907GM", "1.8KG"],
    description: "Advanced whey with creatine.",
    keyBenefits: ["Strength", "Lean mass"],
    nutritionalInfo: "30g protein",
    inStock: true,
  },

  {
    id: "mb-biozyme",
    name: "Biozyme Whey Performance",
    brand: "MuscleBlaze",
    category: "Whey Protein",
    price: 2799,
    originalPrice: 3299,
    discount: 15,
    rating: 4.5,
    reviews: 10200,
    image: "/biozyme.jpg",
    images: ["/biozyme.jpg"],
    flavors: [
      { name: "Rich Chocolate", price: 2799 },
      { name: "Chocolate Hazelnut", price: 2899 },
      { name: "Kesar Thandai", price: 2899 },
      { name: "Magical Mango", price: 2799 },
    ],
    weight: "1KG",
    weights: ["1KG", "2KG"],
    description: "Clinically tested protein.",
    keyBenefits: ["Better digestion"],
    nutritionalInfo: "25g protein",
    inStock: true,
  },

  /* ===================== CREATINE ===================== */

  {
    id: "mb-creatine",
    name: "Creatine Monohydrate",
    brand: "MuscleBlaze",
    category: "Creatine",
    price: 599,
    originalPrice: 699,
    discount: 14,
    rating: 4.7,
    reviews: 15000,
    image: "/creatine.jpg",
    images: ["/creatine.jpg"],
    flavors: [
      { name: "Unflavoured", price: 599 },
      { name: "Citrus Blast", price: 649 },
      { name: "Watermelon Kool Aid", price: 649 },
    ],
    weight: "250GM",
    weights: ["100GM", "250GM", "320GM"],
    description: "Pure creatine monohydrate.",
    keyBenefits: ["Strength", "Power"],
    nutritionalInfo: "3g creatine",
    inStock: true,
  },

  {
    id: "gnc-creatine",
    name: "Creatine Monohydrate",
    brand: "GNC",
    category: "Creatine",
    price: 999,
    originalPrice: 1199,
    discount: 17,
    rating: 4.5,
    reviews: 6700,
    image: "/gnc-creatine.jpg",
    images: ["/gnc-creatine.jpg"],
    flavors: [
      { name: "Unflavoured", price: 999 },
      { name: "Orange", price: 1049 },
      { name: "Blueberry", price: 1049 },
    ],
    weight: "250GM",
    weights: ["100GM", "250GM", "400GM"],
    description: "Micronized creatine.",
    keyBenefits: ["Muscle energy"],
    nutritionalInfo: "5g creatine",
    inStock: true,
  },

  /* ===================== MASS GAINER ===================== */

  {
    id: "mb-mass",
    name: "Mass Gainer",
    brand: "MuscleBlaze",
    category: "Mass Gainer",
    price: 2199,
    originalPrice: 2599,
    discount: 15,
    rating: 4.4,
    reviews: 5400,
    image: "/mass.jpg",
    images: ["/mass.jpg"],
    flavors: [{ name: "Chocolate", price: 2199 }],
    weight: "3KG",
    weights: ["1KG", "3KG", "5KG"],
    description: "High calorie mass gainer.",
    keyBenefits: ["Weight gain"],
    nutritionalInfo: "1250 calories",
    inStock: true,
  },

  /* ===================== PRE WORKOUT ===================== */

  {
    id: "mb-pre",
    name: "Pre Workout 200 Xtreme",
    brand: "MuscleBlaze",
    category: "Pre Workout",
    price: 1499,
    originalPrice: 1799,
    discount: 17,
    rating: 4.3,
    reviews: 3200,
    image: "/pre.jpg",
    images: ["/pre.jpg"],
    flavors: [
      { name: "Fruit Punch", price: 1499 },
      { name: "Tangy Orange", price: 1499 },
    ],
    weight: "200GM",
    weights: ["100GM", "200GM"],
    description: "Explosive energy booster.",
    keyBenefits: ["Focus", "Pump"],
    nutritionalInfo: "200mg caffeine",
    inStock: true,
  },

  /* ===================== MULTIVITAMIN ===================== */

  {
    id: "gnc-mega-men",
    name: "Mega Men Multivitamin",
    brand: "GNC",
    category: "Multivitamin",
    price: 1099,
    originalPrice: 1299,
    discount: 15,
    rating: 4.6,
    reviews: 7800,
    image: "/multivitamin.jpg",
    images: ["/multivitamin.jpg"],
    flavors: [{ name: "Unflavoured", price: 1099 }],
    weight: "60N",
    weights: ["30N", "60N"],
    description: "Complete daily vitamins.",
    keyBenefits: ["Immunity", "Energy"],
    nutritionalInfo: "Daily vitamins",
    inStock: true,
  },
]
